development: &development
  bucket: janani_development
  access_key_id: AKIAJYBWIXLV3SVXG7PA
  secret_access_key: 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

test:
  <<: *development

production:
  <<: *development